### ISSUE TITLE
Unable to install glfw/v3.1

### ISSUE THREAD

**Issue by ghost** [go-gl/glfw#129]
I'm trying to install `github.com/go-gl/glfw/v3.1/glfw` with next command:

```
go get github.com/go-gl/glfw/v3.1/glfw
```

And got following result:

```
# github.com/go-gl/glfw/v3.1/glfw
In file included from ./glfw/src/internal.h:74:0,
                 from ./glfw/src/context.c:28,
                 from ./glfw_context.c:1:
./glfw/src/x11_platform.h:38:33: fatal error: X11/Xcursor/Xcursor.h: No such file or directory
 #include <X11/Xcursor/Xcursor.h>
                                 ^
compilation terminated.
```

I tried on Ubuntu.

```
$ uname -a
Linux localhost 3.13.0-45-generic #74-Ubuntu SMP Tue Jan 13 19:36:28 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by pwaller** [comment]
Do you have `libx11-dev` installed?

**Comment by ghost** [comment]
Yes, sure

```
$ sudo apt-cache policy libx11-dev
libx11-dev:
  Installed: 2:1.6.2-1ubuntu2
  Candidate: 2:1.6.2-1ubuntu2
  Version table:
 *** 2:1.6.2-1ubuntu2 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by pwaller** [comment]
If you run `find /usr/include -name Xcursor.h` do you find anything? What about `/usr/local/include`?

**Comment by tapir** [comment]
I think it's actually `libxcursor-dev`

**Comment by ghost** [comment]
Yeah. I just installed `libxcursor-dev` package, and now it could not find `XInput2.h`

**Comment by ghost** [comment]
`libxi-dev` contains `XInput2.h`, and now it could not find `X11/extensions/Xinerama.h`

**Comment by tapir** [comment]
Isn't there a meta package that gets everything. Something like `xorg-dev`?

**Comment by ghost** [comment]
Finally, after I've installed `libxinerama-dev`, `go get github.com/go-gl/glfw/v3.1/glfw` successfully finished.
Thank you.

**Comment by tapir** [comment]
I've just checked. For future reference the package `xorg-dev` installs everything needed.

**Comment by ghost** [comment]
And what about Windows? There are no `apt-file` utility under Windows to find what I should install.

**Comment by tapir** [comment]
@IvanGL  You can refer to GLFW documents http://www.glfw.org/docs/latest/compile.html#compile_deps
For windows, you don't really need anything.

**Comment by ghost** [comment]
@tapir Thank you.

**Comment by paolov** [comment]
@tapir do you know the package for CentOs? yum cannot find xorg-dev

**Comment by tapir** [comment]
@paolov https://github.com/go-gl/glfw/blob/master/README.md

**Comment by paolov** [comment]
@tapir apologies I arrived here because I have problems compiling glfw on CentOS 7 and in particular I'm missing the xcursor.h headers. Everything else is already installed (headers/library for randr, xinerama, ..). i was wondering if there was other packages similar to xorg-dev that existed in the past. I cant understand why I'm missing only that particular header..

**Comment by tapir** [comment]
@paolov as stated in the README you need libXcursor-devel package. You're probably looking to Debian line whereas you should look at the CentOS line in the README.

**Comment by paolov** [comment]
@tapir the problem is different: I have already all packages you mentioned but missing one header (despite having the library too). Maybe it's because I'm working with a minimal installation so could be another package is required or something went wrong installing those packages. I canr work on the machine right now but I'll do more investigation later

**Comment by tapir** [comment]
As can be seen below libxcursor-devel has the needed file. Are you aboslutely positively sure that you didn't install libxcurser instead of libxcurser-devel? If so then you must have manually deleted it. Try reinstalling and check /usr/include/X11/Xcursor again for the file.

![capture](https://cloud.githubusercontent.com/assets/223984/20751174/706a3a22-b70b-11e6-87c4-5fabc3e9625a.PNG)

**Comment by Megidd** [comment]
openSUSE Leap 15.3 problem is solved by:

```
sudo zypper in xorg-x11-devel
```

**Comment by IsAmogusDead** [comment]
it doesnt look like "xorg-dev" is available on fedora. I have searched from top to bottom and still cant find anything that even talks about xorg-dev on fedora. if anybody is still lurking on this issue, any help would be much appreciated.
